backend:
  name: github
  repo: Anas0473/my-book-library
  branch: main

local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"
media_folder_relative: false

collections:
  - name: "books"
    label: "Books"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author(s)", name: "author", widget: "string" }
      - { label: "ISBN", name: "isbn", widget: "string", required: false }
      - { label: "Publish Date (Year)", name: "pubDate", widget: "string", required: false }
      - { label: "Status", name: "status", widget: "select", options: ["Reading", "Read", "Plan to Read"] }
      - { label: "Cover Image", name: "heroImage", widget: "image", required: false }
      - { label: "Notes / Review", name: "body", widget: "markdown", required: false }